Ramen_Record_APP/app/urls.py
from django.urls import path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .models import Item
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView
from django.conf.urls.static import static
from django.conf import settings

# アプリケーションのルーティング設定

urlpatterns = [
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('', ItemFilterView.as_view(), name='index'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Ramen_Record_APP/config/urls.py
from django.contrib import admin
from django.urls import path, include

# ルーティング設定
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# 管理サイトの見出しを変更可能
#  タイトル；タイトルタグで使用
admin.site.site_title = 'タイトル'
#  サイト名：ログイン画面と管理画面上部の表示
admin.site.site_header = '店舗記録アプリ'
#  メニュー：管理画面の見出し表示
admin.site.index_title = 'メニュー'

Ramen_Record_APP/app/models.py
from django.db import models
from django.contrib.admin.widgets import AdminDateWidget
from django import forms

from users.models import User


class Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/2.1/ref/models/fields/
    """
    
    name = models.CharField(
       verbose_name='ラーメン店',
       max_length=20,
       blank=True,
       null=True,
    )
    
    name1 = models.CharField(
       verbose_name='メニュー名称',
       max_length=20,
       blank=True,
       null=True,
    )

    name2 = models.CharField(
        verbose_name='都道府県',
        max_length=20,
        blank=True,
        null=True,
    )
    
    name3 = models.CharField(
        verbose_name='市区町村',
        max_length=20,
        blank=True,
        null=True,
    )
    
    
    ramen_taste = (
        ('醤油', '醤油'),
        ('塩', '塩'),
        ('豚骨', '豚骨'),
        ('味噌', '味噌'),
        ('鯛', '鯛'),
        ('鶏白湯', '鶏白湯'),
        ('つけ麺', 'つけ麺'),
        ('担々麺', '担々麺'),
        ('油そば', '油そば'),
       
    )

    # サンプル項目1 ラーメンの味
    sample_1 = models.TextField(
        verbose_name='味',
        choices=ramen_taste,
        blank=True,
        null=True,
    )
    
    
    # サンプル項目2 満足度合い
    sample_satisfaction = models.IntegerField(
        verbose_name='満足度評価',
        blank=True,
        null=True,
    )

   # サンプル項目3 こってり度合い 
    sample_3 = models.IntegerField(
        verbose_name='こってり度評価',
        blank=True,
        null=True,
    )

    # サンプル項目4 辛さ度合い　(削除)
    sample_4 = models.IntegerField(
        verbose_name='からさ評価',
        blank=True,
        null=True,
    )
    
    #サンプル項目　麺の太さ
    ramen_hutosa = (
        (1, '極細麺(1.1mm)'),
        (2, '細麺(1.15mm)'),
        (3, '中細麺(1.25mm)'),
        (4, '中太麺(1.4mm)'),
        (5, '太麺(1.7〜1.875mm)'),
        (6, '極太麺(2.2〜2.5mm)'),
    )
    
    sample_menhutosa = models.IntegerField(
        verbose_name='麺の太さ',
        choices=ramen_hutosa,
        blank=True,
        null=True,
    )
    
    # サンプル項目5 値段評価
    sample_5 = models.IntegerField(
        verbose_name='値段評価',
        blank=True,
        null=True,
    )
    
    #サンプル項目5.1 値段
    sample_cost = models.CharField(
        verbose_name='値段',
        max_length=10,
        blank=True,
        null=True,
    )
    
    # サンプル項目6 アクセス
    sample_6 = models.IntegerField(
        verbose_name='アクセス評価',
        blank=True,
        null=True,
    )

    #サンプル項目 URL
    sample_url = models.URLField(
        verbose_name='ホームページ',
        max_length=100,
        blank=True,
        null=True,
    )
    
    #サンプル項目8 感想
    memo = models.TextField(
        verbose_name='コメント欄',
        max_length=300,
        blank=True,
        null=True,
    )
    
    #サンプル項目9 来店日付
    date = models.DateField(blank=True, null=True)
    
    #サンプル項目10 画像
    image = models.ImageField(
        upload_to = '',
        verbose_name='添付画像',
        null=True,
        blank=True,
    )
    

    
    # 以下、管理項目

    # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成時間
    created_at = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        editable=False,
    )

    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新時間
    updated_at = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        editable=False,
    )


    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.name

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'サイト'
        verbose_name_plural = 'サイト'

Ramen_Record_APP/app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>サンプルアプリ</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-info ">
     <!-- サイト表示(上部画面設定) -->
    <a class="navbar-brand" href="#">店舗記録内容</a>
  
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">管理画面</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">ログアウト</a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"
        charset="UTF-8"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ja.min.js"></script>
<script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
<script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

Ramen_Record_APP/app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">

    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="page-item disabled pagination-prev">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for page in paginator.page_range %}
        {% if page == page_obj.number %}
            <li class="page-item active">
                <span class="page-link">{{ page }} <span class="sr-only">(current)</span></span>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
            </li>
        {% endif %}
    {% endfor %}

     <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="page-item disabled pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

Ramen_Record_APP/app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}

<div class="container-fluid bg-secondary text-white">
 <div class="container bg-light text-dark">
     <h2 class="text-center">データ削除</h2>
         <p>このデータを削除します。よろしいですか？</p>
     <div class="container bg-light text-dark">
         <form action="" method="post">
            {% csrf_token %}
            {% include "./item_detail_contents.html" %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right mb-3">
                        <a class="btn btn-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-dark delete" value="削除"/>
                    </div>
                </div>
            </div>
        </form>
     </div>
 </div>
</div>
{% endblock %}

Ramen_Record_APP/app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
<div class="container-fluid bg-secondary text-white">
    <div class="container bg-light text-dark">
        <h2 class="text-center">詳細表示</h2>
        <!--  -->
        {% include "./item_detail_contents.html" %}
        <div class="row">
            <div class="col-12 d-flex justify-content-end">
                <a class="btn btn-dark" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
        
    </div>
</div>
{% endblock %}

Ramen_Record_APP/app/templates/app/item_detail_contents.html
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">ラーメン店</div>
    <div class="col pt-3 border">
        <p>{{item.name|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">メニュー名称</div>
    <div class="col pt-3 border">
        <p>{{item.name1|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">都道府県</div>
    <div class="col pt-3 border">
        <p>{{item.name2|default_if_none:"未入力"}}</p>
    </div>
</div>
    
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">市区町村</div>
    <div class="col pt-3 border">
        <p>{{item.name3|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">味</div>
    <div class="col pt-3 border">
        <p>{{item.sample_1|default_if_none:"未入力"}}</p>
    </div>
</div>
    
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">満足度評価</div>
    <div class="col pt-3 border">
        <p>{{item.sample_satisfaction|default_if_none:"未入力"}}</p>
    </div>
</div>
    
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">こってり度評価</div>
    <div class="col pt-3 border">
        <p>{{item.sample_3|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">麺の太さ評価</div>
    <div class="col pt-3 border">
        <p>{{item.sample_menhutosa|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">値段評価</div>
    <div class="col pt-3 border">
        <p>{{item.sample_5|default_if_none:"未入力"}}</p>
    </div>
</div>

    
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">コメント</div>
    <div class="col pt-3 border">
        <p>{{item.memo|default_if_none:"未入力"}}</p>
    </div>
</div>

<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">来店日時</div>
    <div class="col pt-3 border">
        <p>{{item.date|default_if_none:"未入力"}}</p>
    </div>
</div>
    
<div class="row mx-md-n5">
　<div class="col-2 pt-3 border bg-light">ホームページ</div>
    <div class="col pt-3 border">
        <a href="{{item.sample_url }}">{{item.sample_url}}</a>
    </div>
</div>

Ramen_Record_APP/app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <div class="container-fluid bg-secondary text-white">
        <!-- 検索モーダル -->
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <!-- 検索機能一覧設定 -->
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" style="color: black;">検索条件</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body" style="color: black;">
                  
                        </div>    
                    </form>
                    
                    <div class="modal-footer">
                        <a class="btn btn-dark" data-dismiss="modal">戻る</a>
                        <button type="submit" class="btn btn-dark" form="filter">検索</button>
                    </div>
                </div>
            </div>
        </div>

        <!-- 新規、検索ボタン設定 -->
        <div class="row">
            <div class="col-12">
                <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                <div class="float-right mt-1">
                    <a class="btn btn-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>

        <!-- サイト表示一覧 -->

        <div class="row mt-3">
            <div class="col-12 p-3 mb-12">
                <ul class="list-group">
                    {% if item_list %}
                        {% for item in item_list %}
                            <li class="list-group-item bg-light text-dark">
                                {# item_detail_contents.html を参考に必要な項目を追加してください #}
                                <div class="row">
                                    <div class="col-9">
                                        <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>1_ラーメン店</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.name | default_if_none:"未入力" }}</p>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>2_メニュー名称</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.name1 | default_if_none:"未入力" }}</p>
                                            </div>
                                          </div>
                                        
                                          <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>3_都道府県</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.name2 | default_if_none:"未入力" }}</p>
                                            </div>
                                          </div>
                                                
                                          <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>4_市区町村</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.name3 | default_if_none:"未入力" }}</p>
                                            </div>
                                          </div>
                                        
                                          <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>5_スープ</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.get_sample_1_display | default_if_none:"未入力" }}</p>
                                            </div>
                                          </div>
                                        
                                          <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>6_満足度評価</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.sample_satisfaction | default_if_none:"未入力" }}</p>
                                            </div>
                                         </div>
                                        
                                          <div class="row">
                                            <div class="col-2 offset-2">
                                                <p>7_来店日時</p>
                                            </div>
                                            <div class="col-4 offset-2">
                                                <p>{{ item.date | default_if_none:"未入力" }}</p>
                                            </div>
                                          </div>
                                         </div>        
                                         
                                    <div class="col-3 clearfix">
                                        {% if item.image %}
                                            <p><img src='{{item.image.url}}' class="img-fluid" width=250></p>
                                        {% endif %}
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-12">
                                        <div class="float-right">
                                            <a class="btn btn-dark" href="{% url 'detail' item.pk %}">詳細</a>
                                            <a class="btn btn-dark" href="{% url 'update' item.pk %}">編集</a>
                                            <a class="btn btn-dark" href="{% url 'delete' item.pk %}">削除</a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item">
                            <p>対象のデータがありません</p>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <!-- ページ番号ボタン設定 -->

        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
    </div>
{% endblock %}

Ramen_Record_APP/app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form.certifications.errors }}

    <div class="container-fluid bg-secondary text-white">
       
        <div class="row">
            <div class="col-12">
                <h2 class="text-center">登録・更新</h2>
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-12 p-3 mb-12">
                <form method="post" id="myform" enctype="multipart/form-data">
                    {% crispy form %}
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="float-right mb-3">
                    <a class="btn btn-dark" href="{% url 'index' %}">戻る</a>
                    <a class="btn btn-dark save" href="#">保存</a>
                </div>
            </div>
        </div>
        
    </div>

{% endblock %}